accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, PasswordChangeView 
from .forms import LoginForm


app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/',  LoginView.as_view(template_name="registration/login.html", authentication_form=LoginForm ),  name='login'),
    
    
    
]

urlpatterns += [
    path('<str:username>', views.userpage, name='user_link'),
    
]

urlpatterns += [
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    
]

home/urls.py
from . import views
from django.urls import path



app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/settings/', views.user_setting, name='user_settings'),
    path('dashboard/change_pass/', views.password_change, name='change_pass'),    
]


urlpatterns += [
    path('dashboard/calender/', views.calender, name='calender'),    
    path('dashboard/components_form/', views.components_form, name='components_form'),    
    path('dashboard/components_model/', views.components_model, name='components_model'),    
    path('dashboard/components_notifications/', views.components_notifications, name='components_notifications'),    
    path('dashboard/components_typography/', views.components_typography, name='components_typography'), 
]


urlpatterns += [
    path('dashboard/all_traffic/', views.all_traffic, name='all_traffic'),    
    path('dashboard/product_analysis/', views.product_analysis, name='product_analysis'),    
    path('dashboard/kanban/', views.kanban, name='kanban'),    
    path('dashboard/message/', views.message, name='message'),    
    path('dashboard/users/', views.users, name='users'), 
]


urlpatterns += [
    path('dashboard/transactions/', views.transactions, name='transactions'),    
    path('dashboard/tasks/', views.tasks, name='tasks'),    
    path('dashboard/map/', views.map, name='map'),    
    path('dashboard/datatables/', views.datatables, name='datatables'),    
    path('dashboard/bootstrap_tables/', views.bootstrap_tables, name='bootstrap_tables'), 
]


urlpatterns += [
    path('dashboard/pricing/', views.pricing, name='pricing'),    
    path('dashboard/billing/', views.billing, name='billing'),    
    path('dashboard/invoice/', views.invoice, name='invoice'),    
    path('dashboard/page_signin/', views.page_signin, name='page_signin'),    
    path('dashboard/page_signup/', views.page_signup, name='page_signup'), 
]

urlpatterns += [
    path('dashboard/page_forget_password/', views.page_forget_password, name='page_forget_password'),    
    path('dashboard/page_reset_password/', views.page_reset_password, name='page_reset_password'),    
    path('dashboard/page_lock/', views.page_lock, name='page_lock'),    
    path('dashboard/page_404/', views.page_404, name='page_404'),    
    path('dashboard/page_500/', views.page_500, name='page_500'), 
]

urlpatterns += [
    path('dashboard/buttons/', views.buttons, name='buttons'),    
    path('dashboard/widgets/', views.widgets, name='widgets'),    
    path('dashboard/page_lock/', views.page_lock, name='page_lock'),    
    path('dashboard/page_404/', views.page_404, name='page_404'),    
    path('dashboard/page_500/', views.page_500, name='page_500'), 
]


urlpatterns += [
    path('dashboard/lotto/', views.lotto, name='lotto'),    
    path('dashboard/sports/', views.sports, name='sports'),    
    path('dashboard/crypto/', views.crypto, name='crypto'),    
    
]

templates/includes/footer-presentation.html
<footer class="footer py-6 bg-gray-800 text-white">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <img class="navbar-brand-dark mb-4" height="35" src="/static/assets/img/brand/light.svg" alt="Logo light">
                    <p class="text-gray-300">Volt is a Premium Bootstrap 5 Admin Dashboard bringing together beautiful UI/UX design and functional elements.</p>
                    <ul class="social-buttons mb-5 mb-lg-0">
                        <li>
                            <a href="https://twitter.com/themesberg" aria-label="twitter social link" class="d-flex align-item-center">
                                <svg class="icon icon-xs text-white" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="twitter" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/themesberg/" class="d-flex align-item-center" aria-label="facebook social link">
                                <svg class="icon icon-xs text-white" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-f" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/themesberg" aria-label="github social link" class="d-flex align-item-center">
                                <svg class="icon icon-xs text-white" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="github" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path></svg>
                            </a>
                        </li>
                        <li>
                            <a href="https://dribbble.com/themesberg" class="d-flex align-item-center" aria-label="dribbble social link" >
                                <svg class="icon icon-xs text-white" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="dribbble" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 8C119.252 8 8 119.252 8 256s111.252 248 248 248 248-111.252 248-248S392.748 8 256 8zm163.97 114.366c29.503 36.046 47.369 81.957 47.835 131.955-6.984-1.477-77.018-15.682-147.502-6.818-5.752-14.041-11.181-26.393-18.617-41.614 78.321-31.977 113.818-77.482 118.284-83.523zM396.421 97.87c-3.81 5.427-35.697 48.286-111.021 76.519-34.712-63.776-73.185-116.168-79.04-124.008 67.176-16.193 137.966 1.27 190.061 47.489zm-230.48-33.25c5.585 7.659 43.438 60.116 78.537 122.509-99.087 26.313-186.36 25.934-195.834 25.809C62.38 147.205 106.678 92.573 165.941 64.62zM44.17 256.323c0-2.166.043-4.322.108-6.473 9.268.19 111.92 1.513 217.706-30.146 6.064 11.868 11.857 23.915 17.174 35.949-76.599 21.575-146.194 83.527-180.531 142.306C64.794 360.405 44.17 310.73 44.17 256.323zm81.807 167.113c22.127-45.233 82.178-103.622 167.579-132.756 29.74 77.283 42.039 142.053 45.189 160.638-68.112 29.013-150.015 21.053-212.768-27.882zm248.38 8.489c-2.171-12.886-13.446-74.897-41.152-151.033 66.38-10.626 124.7 6.768 131.947 9.055-9.442 58.941-43.273 109.844-90.795 141.978z"></path></svg>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-6 col-md-2 mb-5 mb-lg-0">
                    <span class="h5">Themesberg</span>
                    <ul class="links-vertical mt-2">
                        <li><a target="_blank" href="https://themesberg.com/blog">Blog</a></li>
                        <li><a target="_blank" href="https://themesberg.com/products">Products</a></li>
                        <li><a target="_blank" href="https://themesberg.com/about">About Us</a></li>
                        <li><a target="_blank" href="https://themesberg.com/contact">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-2 mb-5 mb-lg-0">
                    <span class="h5">Other</span>
                    <ul class="links-vertical mt-2">
                        <li><a href="https://themesberg.com/docs/volt-bootstrap-5-dashboard/getting-started/quick-start/" target="_blank">Docs
                                <span class="badge badge-sm bg-secondary text-dark ms-2">v1.4</span></a></li>
                        <li><a href="https://themesberg.com/docs/volt-bootstrap-5-dashboard/getting-started/changelog/" target="_blank">Changelog</a></li>
                        <li><a target="_blank" href="https://themesberg.com/licensing">License</a>
                        </li>
                        <li><a target="_blank" href="https://themesberg.com/contact">Support</a></li>
                    </ul>
                </div>
                <div class="col-12 col-md-4 mb-5 mb-lg-0">
                    <span class="h5 mb-3 d-block">Subscribe</span>
                    <form action="#">
                        <div class="form-row mb-2">
                            <div class="col-12">
                                <input type="email" class="form-control mb-2" placeholder="example@company.com" name="email" aria-label="Subscribe form" required>
                            </div>
                            <div class="col-12 d-grid">
                                <button type="submit" class="btn btn-secondary" data-loading-text="Sending">
                                    <span>Subscribe</span>
                                </button>
                            </div>
                        </div>
                    </form>
                    <p class="text-muted font-small m-0">We’ll never share your details. See our <a class="text-white" href="#">Privacy Policy</a></p>
                </div>
            </div>
            <hr class="bg-gray-700 my-5">
            <div class="row">
                <div class="col mb-md-0">
                    <a href="https://themesberg.com" target="_blank" class="d-flex justify-content-center">
                        <img src="/static/assets/img/themesberg-logo-alt.svg" height="35" class="mb-4" alt="Themesberg Logo">
                    </a>
                <div class="d-flex text-center justify-content-center align-items-center" role="contentinfo">
                    <p class="font-weight-normal font-small mb-0">&copy; Themesberg - Coded by AppSeed.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/includes/footer.html
<footer class="bg-white rounded shadow p-5 mb-4 mt-4">
                <div class="row">
                    <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0">
                        <p class="mb-0 text-center text-lg-start">
                            &copy; Themesberg - coded by AppSeed.
                        </p>
                    </div>
                    <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">
                        <!-- List -->
                        <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">
                            <li class="list-inline-item px-0 px-sm-2">
                                <a target="_blank" href="https://appseed.us/admin-dashboards/django-dashboard-volt-pro">Django Dashboard Volt PRO</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </footer>
            

templates/includes/l_form.html
<div class="col-12 d-flex align-items-center justify-content-center">
    <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
        <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h3">
                Django Volt PRO - Login
            </h1>
            <br />
            <span class="mb-0 text-muted">
                {% if messages %}  
                <div class="col-12 text-center">
                    <div class="alert alert-secondary shadow-soft" role="alert">                            
                        {% for message in messages %}
                        <span class="alert-inner--text">{{ message }}</span>
                        {% endfor %}                            
                    </div>                        
                </div>
                {% else %}
                    Add your credentials
                {% endif %} 




{% if form.non_field_errors %}

{% for error in form.non_field_errors %}

{{ error }}

{% endfor %}

{% endif %} 







            </span>                                
        </div>
        <form method="post" action="" class="mt-4">

            {% csrf_token %}

            {{form.as_p}}


            

            
            <div class="d-grid">
                <button type="submit" name="login" class="btn btn-gray-800">Sign in</button>
            </div>
        </form>
        <br />
        <!-- End of Form -->
        <div class="d-flex justify-content-between align-items-top mb-4">
            <div>
                <a href="{% url 'password_reset' %}" class="small text-right">Forget Password?Reset!</a>
            </div>
            <div>
                <a href="{% url 'accounts:signup' %}" class="small text-right">No Account? Signup</a>
            </div>
        </div>
    </div>
</div>

templates/includes/navigation-presentation.html
<header class="header-global">
        <nav id="navbar-main" aria-label="Primary navigation" class="navbar navbar-main navbar-expand-lg navbar-theme-primary pt-4 navbar-dark">
            <div class="container position-relative">
                <div class="navbar-collapse collapse me-auto" id="navbar_global">
                    <div class="navbar-collapse-header">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a href="/">
                                    <img src="/static/assets/img/brand/light.svg" alt="Volt logo">
                                </a>
                            </div>
                            <div class="col-6 collapse-close">
                                <a href="#navbar_global" class="fas fa-times" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" title="close" aria-label="Toggle navigation"></a>
                            </div>
                        </div>
                    </div>
                    <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
                        <li class="nav-item me-2">
                            <a href="{% url 'home:dashboard' %}" class="nav-link">Dashboard</a>
                        </li>
                        <li class="nav-item me-2">
                            <a href="{% url 'home:pricing' %}" class="nav-link">Pricing</a>
                        </li>
                        <li class="nav-item me-2">
                            <a href="{% url 'home:user_settings' %}" class="nav-link">Settings</a>
                        </li>
                    </ul>
                </div>
                <div class="d-flex align-items-center ms-auto">
                    {% if user.is_authenticated %}
                <span class="me-3"> Hi {{ user.username }}!</span>
                <a href="{% url 'logout' %}" class="btn btn-outline-white d-inline-flex align-items-center me-md-3">Log Out</a>
                <a href="{% url 'password_reset' %}" class="btn btn-outline-white d-inline-flex align-items-center me-md-3">Reset Password</a>
                {% else %}
                
                <a href="{% url 'login' %}" class="btn btn-outline-white d-inline-flex align-items-center me-md-3">Log In</a>
                
                {% endif %}
                </div>
            </div>
        </nav>
    </header>

templates/includes/scripts.html
<!-- Core Libs -->
<script src="/static/assets/vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Plugins -->
<script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>
<script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>
<script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
<script src="/static/assets/vendor/countup.js/dist/countUp.umd.js"></script>
<script src="/static/assets/vendor/apexcharts/dist/apexcharts.min.js"></script>
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>
<script src="/static/assets/vendor/simple-datatables/dist/umd/simple-datatables.js"></script>
<script src="/static/assets/vendor/sweetalert2/dist/sweetalert2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>
<script src="/static/assets/vendor/fullcalendar/main.min.js"></script>
<script src="/static/assets/vendor/dropzone/dist/min/dropzone.min.js"></script>
<script src="/static/assets/vendor/choices.js/public/assets/scripts/choices.min.js"></script>
<script src="/static/assets/vendor/notyf/notyf.min.js"></script>
<script src="/static/assets/vendor/leaflet/dist/leaflet.js"></script>
<script src="/static/assets/vendor/svg-pan-zoom/dist/svg-pan-zoom.min.js"></script>
<script src="/static/assets/vendor/svgmap/dist/svgMap.min.js"></script>
<script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>
<script src="/static/assets/vendor/sortablejs/Sortable.min.js"></script>

<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<script src="/static/assets/js/volt.js"></script>